---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aypvkhag/globalblockfarm.com/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R server $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
